---

- hosts: all
  become: true
  tasks: 

  - name: Install Apache & PHP packages
    package:
            name: 
                - "{{apache_package}}"
                - "{{php_package}}"
            state: latest
            update_cache: yes

  - name: "Copying File"
    tags: apache2
    copy:
            src: default_site.html
            dest: /tmp/index.html
            owner: root
            group: root
            mode: 0644
